# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=60)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp', models.IntegerField()),
                ('wind_speed', models.CharField(max_length=20)),
                ('wind_direction', models.CharField(max_length=20)),
                ('conditions', models.CharField(max_length=60)),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forecast_app.City')),
            ],
        ),
    ]
